from django.conf.urls import patterns, url
from share.views import ResetPasswordRequestView
urlpatterns = patterns('',
    url(r'^$', 'share.views.index', name='index'),
    url(r'^tags/$', 'share.views.tags', name='tags'),
    url(r'books/$', 'share.views.books', name='books'),
    url(r'^about/$', 'share.views.about', name='about'),
    url(r'^news/$', 'share.views.get_news', name='get_news'),
    url(r'^submit/$', 'share.views.submit', name='submit'),
    url(r'^search/$', 'share.views.search', name='search'),
    url(r'^login/$', 'share.views.user_login', name='login'),
    url(r'^profile/$', 'share.views.profile', name='profile'),
    url(r'^goto/$', 'share.views.track_url', name='track_url'),
    url(r'^logout/$', 'share.views.user_logout', name='logout'),
    url(r'^register/$', 'share.views.register', name='register'),
    url(r'^likes_news/$', 'share.views.likes_news', name='likes_news'),
    url(r'^likes_book/$', 'share.views.likes_book', name='likes_book'),
    url(r'^vote_comment/$', 'share.views.vote_comment', name='vote_comment'),
    url(r'^dislikes_news/$', 'share.views.dislikes_news', name='dislikes_news'),
    url(r'^like_tag/$', 'share.views.like_tag', name='like_tag'),
    url(r'^auto_add_news/$', 'share.views.auto_add_news', name='auto_add_new'),
    #url(r'^password_reset/$', 'share.views.password_reset', name='password_reset'),
    url(r'^suggest_news/$', 'share.views.suggest_news', name='suggest_news'),
    url(r'^tag_news/(?P<tag_name_url>\w+)/$', 'share.views.tag_news', name='tag_news'),
    url(r'^user/(?P<author>\w+)/$', 'share.views.user_profile', name='user_profile'),
    url(r'^news/(?P<news_id>\w+)/comments/$', 'share.views.add_comment', name='add_comment'),
    url(r'^add_comment/(?P<news_id>\w+)/$', 'share.views.add_comment', name='add_comment'),
    url(r'^reset_password/$', 'share.views.reset_password', name='change_password'),
    url(r'^book_list/(?P<tag_name_url>\w+)/$', 'share.views.get_books', name='get_books'),
    url(r'^forgot_password', ResetPasswordRequestView.as_view(), name="reset_password"),
    url(r'^tag/(?P<tag_name_url>\w+)/add_news/$', 'share.views.add_news', name='add_new'),
)